version = 0.1
[default.deploy.parameters]
stack_name = "cognito-react-jv"
resolve_s3 = true
s3_prefix = "cognito-react-jv"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"dev\" S3BucketName=\"joanv22-static-site\" CognitoUserPoolName=\"joanv22-userpool\" CognitoWebClientName=\"joanv22-webclient\""
image_repositories = []
